SHOW VARIABLES LIKE 'sched_affinity_foreground_thread';
SHOW VARIABLES LIKE 'sched_affinity_log_writer';
SHOW VARIABLES LIKE 'sched_affinity_log_flusher';
SHOW VARIABLES LIKE 'sched_affinity_log_write_notifier';
SHOW VARIABLES LIKE 'sched_affinity_log_flush_notifier';
SHOW VARIABLES LIKE 'sched_affinity_log_checkpointer';
SHOW VARIABLES LIKE 'sched_affinity_purge_coordinator';
SHOW VARIABLES LIKE 'sched_affinity_numa_aware';